version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/code
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: .
    volumes:
      - ./:/code
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caissesav
      MYSQL_USER: savuser
      MYSQL_PASSWORD: S@v_Plus!2024 
    ports:
      - "4506:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
